### ISSUE TITLE
Any tools for creating binary masks?

### ISSUE THREAD

**Issue by chandu47** [igorcmoura/inpaint-object-remover#1]

**Comment by igorcmoura** [comment]
I don't know any. I use [GIMP](https://www.gimp.org/).

The way I do is like this:
- Use any of the selection tools (e.g.: _Free Select Tool_) to select the area for the mask.
- Select the _Bucket Fill Tool_ (Shift+B).
- Activate the _Fill whole selection_ option.
- Paint the mask foreground white.
- _Invert selection_ (Ctrl+I).
- Paint the background black.
- _Export_ (Ctrl+Shift+E) and save it as JPG.
